### ISSUE TITLE
ld: framework not found Birdbrain

### ISSUE THREAD

**Issue by joobei** [jordenhill/Birdbrain#7]
Hello :)

I opened up the birdbrain project but it fails to build. The error message is ld: framework not found Birdbrain. I can't see why the linked would need to find the Birdbrain framework in order to link the framework to begin with. It's like trying to link with itself ... 

I'm on Xcode 7.2.1

Here is the detailed error message:

Ld /Users/jubei/Library/Developer/Xcode/DerivedData/Birdbrain-ccpqedrlqhtglybhribchsdjwtsj/Build/Products/Debug/Birdbrain.framework/Versions/A/Birdbrain normal x86_64
    cd /Users/jubei/coding/Birdbrain
    export MACOSX_DEPLOYMENT_TARGET=10.11
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -L/Users/jubei/Library/Developer/Xcode/DerivedData/Birdbrain-ccpqedrlqhtglybhribchsdjwtsj/Build/Products/Debug -F/Users/jubei/Library/Developer/Xcode/DerivedData/Birdbrain-ccpqedrlqhtglybhribchsdjwtsj/Build/Products/Debug -filelist /Users/jubei/Library/Developer/Xcode/DerivedData/Birdbrain-ccpqedrlqhtglybhribchsdjwtsj/Build/Intermediates/Birdbrain.build/Debug/Birdbrain.build/Objects-normal/x86_64/Birdbrain.LinkFileList -install_name @rpath/Birdbrain.framework/Versions/A/Birdbrain -Xlinker -rpath -Xlinker @executable_path/../Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -mmacosx-version-min=10.11 -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx -Xlinker -add_ast_path -Xlinker /Users/jubei/Library/Developer/Xcode/DerivedData/Birdbrain-ccpqedrlqhtglybhribchsdjwtsj/Build/Intermediates/Birdbrain.build/Debug/Birdbrain.build/Objects-normal/x86_64/Birdbrain.swiftmodule -framework Metal -framework Accelerate -framework Birdbrain -single_module -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/jubei/Library/Developer/Xcode/DerivedData/Birdbrain-ccpqedrlqhtglybhribchsdjwtsj/Build/Intermediates/Birdbrain.build/Debug/Birdbrain.build/Objects-normal/x86_64/Birdbrain_dependency_info.dat -o /Users/jubei/Library/Developer/Xcode/DerivedData/Birdbrain-ccpqedrlqhtglybhribchsdjwtsj/Build/Products/Debug/Birdbrain.framework/Versions/A/Birdbrain

ld: framework not found Birdbrain
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by joobei** [comment]
I found the problem, the Birdbrain.framework target, has itself as a link target. If I remove that building succeeds.

**Comment by jordenhill** [comment]
Sorry about that! I must have added it by accident during some tests I was doing. I committed it with that removed to prevent people from getting this error again.
